# link-spyder CI/CD Pipeline
name: Develop-branch

# Github Action triggers
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# CI Jobs
jobs:
  lint:
    # Runner
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    # CI Steps
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }} for lint
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install dependecies
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      # Execute linter
      - name: Tox lint
        run: |
          tox -e lint
