# link-spyder CI/CD Pipeline
name: Develop-branch

# Github Action triggers
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# CI Jobs
jobs:
  ci:
    # Runner
    runs-on: ubuntu-latest

    # CI Steps
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: flake8
        run: |
          pip install flake8
          flake8 linkspyder --per-file-ignores=validators.py:E501
